### PR TITLE
Update to terraform version 0.7.0

### PR DESCRIPTION
**Pull request by netflash**

### CODE REVIEW

**Comment by toddmichael** [comment]
Looks good.

**Comment by netflash** [comment]
`kitchen test` for all the linux works good. Can't test for windows

**Comment by haidangwa** [comment]
Personally, I object to PR's that aren't adding anything other than updating the version of terraform. To an end-user of this cookbook, the same can be accomplished simply by using chef the way it's meant to be -- set the version of terraform you want to use in a role or environment setting. I don't know that it's worth anybody's time/effort to keep tracking every release of terraform this way.

**Comment by netflash** [comment]
Well, fair enough. 
Feel free to merge this or close.

Thanks!

**Pull request closed without merging**
